# Generated by Django 3.0.1 on 2022-08-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='watch_details',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
