# Generated by Django 3.0.1 on 2022-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220821_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='watch_details',
            field=models.TextField(),
        ),
    ]
