# Generated by Django 3.0.1 on 2022-08-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotion',
        ),
    ]
