# Generated by Django 3.0.1 on 2022-08-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20220822_1257'),
        ('products', '0004_auto_20220822_1300'),
    ]

    operations = [
    ]
