# Generated by Django 3.0.1 on 2022-08-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_merge_20220822_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='watch_details',
            new_name='product_details',
        ),
    ]
