# Generated by Django 3.0.1 on 2022-08-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20220822_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_details',
        ),
    ]
